export enum Configuration {
  PORT = 'PORT',
  CONNECTION = 'CONNECTION',
  HOST = 'HOST',
  DBPORT = 'DBPORT',
  USERNAME = 'USERNAME',
  PASSWORD = 'PASSWORD',
  DATABASE = 'DATABASE',
  SYNCHRONIZE = 'SYNCHRONIZE',
  LOGGING = 'LOGGING',
  ENTITIES = 'ENTITIES',
  MIGRATIONS = 'MIGRATIONS',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_SECRET = 'GOOGLE_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  JWT_SECRET = 'JWT_SECRET',
  SEND_GRID_KEY = 'SEND_GRID_KEY'
}
